singleServerConfig:
  # 数据库编号
  database: 0
  # 命令等待超时，单位：毫秒
  timeout: 3000
  # 连接池大小
  connectionPoolSize: 64
  # 连接空闲超时，单位：毫秒
  idleConnectionTimeout: 10000
  # 连接超时，单位：毫秒
  connectTimeout: 10000
#  address: "redis://127.0.0.1:6379"