spring:
  datasource:
    url: jdbc:mysql://154.198.227.65:3306/xtzn_lpm?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: JGOp&7%XPb
  redis:
    host: 154.198.227.65
    port: 6379
    password: JGOp&7%XPb
    lettuce:
      pool:
        max-active: 30
        max-wait: -1
        max-idle: 8
        min-idle: 0
  redisson:
    config: classpath:config/redisson-prod.yaml

mybatis-plus:
  type-aliases-package: com.example.lpm.entity
  configuration:
    # mybatis-plus配置控制台打印完整带参数SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

xxl:
  job:
    admin:
      # admin 123456
      addresses: http://27.102.106.249:28080/xxl-job-admin
    executor:
      appname: lpm-service
      ip:  #执行器IP，默认为空表示自动获取IP
      port: 9999 #xxljob配置的端口号，默认为9999
    accessToken: default_token   #调度中心通讯TOKEN [选填]：非空时启用